#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ciso8601
Version  : 2.1.3
Release  : 4
URL      : https://files.pythonhosted.org/packages/2c/da/626910cf8aca7ed2d5b34355eee8aeaaeb6ddd4e16f98d00a9e2ddad3a08/ciso8601-2.1.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/2c/da/626910cf8aca7ed2d5b34355eee8aeaaeb6ddd4e16f98d00a9e2ddad3a08/ciso8601-2.1.3.tar.gz
Summary  : Fast ISO8601 date time parser for Python written in C
Group    : Development/Tools
License  : MIT
Requires: ciso8601-license = %{version}-%{release}
Requires: ciso8601-python = %{version}-%{release}
Requires: ciso8601-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : nose
BuildRequires : pytz
BuildRequires : pytz-python
BuildRequires : testscenarios
BuildRequires : tox

%description
ciso8601
        ========

%package license
Summary: license components for the ciso8601 package.
Group: Default

%description license
license components for the ciso8601 package.


%package python
Summary: python components for the ciso8601 package.
Group: Default
Requires: ciso8601-python3 = %{version}-%{release}

%description python
python components for the ciso8601 package.


%package python3
Summary: python3 components for the ciso8601 package.
Group: Default
Requires: python3-core
Provides: pypi(ciso8601)

%description python3
python3 components for the ciso8601 package.


%prep
%setup -q -n ciso8601-2.1.3
cd %{_builddir}/ciso8601-2.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1601678023
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ciso8601
cp %{_builddir}/ciso8601-2.1.3/LICENSE %{buildroot}/usr/share/package-licenses/ciso8601/51613ab38cfc21e45938a266fd16b66914821c69
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ciso8601/51613ab38cfc21e45938a266fd16b66914821c69

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
